### ISSUE TITLE
error message spew: pocketsphinx

### ISSUE THREAD

**Issue by linas** [hansonrobotics/hrtool#13]
After following instructions for the README, installing and starting:
```
hr run robot
tmux a
```
Terminal 0 shows a fast spew of messages. One of these is:
```
Traceback (most recent call last):
  File "/home/hanson/hansonrobotics/HEAD/src/audio_stream/scripts/audio_sensor.py", line 21, in <module>
    from pocketsphinx.pocketsphinx import *
ImportError: No module named pocketsphinx.pocketsphinx
```

So I guess that needs to be installed!? Apparently, the hrtool install stage did not install it!?

**Comment by linas** [comment]
Am attempting to fix this by `apt-get install ros-indigo-pocketsphinx` ...

**Comment by linas** [comment]
OK, that does not fix the problem.  Attempting to fix this with `apt-get install python-pocketsphinx`...

**Comment by linas** [comment]
OK, so `apt-get install python-pocketsphinx` does move forward: there is now a different error:

```
Traceback (most recent call last):
  File "/home/hanson/hansonrobotics/HEAD/src/audio_stream/scripts/audio_sensor.$y", line 21, in <module>
    from pocketsphinx.pocketsphinx import *
  File "sphinxbase.pxd", line 150, in init pocketsphinx (pocketsphinx.c:7935)
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object
```

**Comment by linas** [comment]
The `hr install -f head` as suggested in issue #12 makes this problem go away.
