### ISSUE TITLE
error message spew: motor assemblies

### ISSUE THREAD

**Issue by linas** [hansonrobotics/hrtool#14]
After following instructions for the README, installing and starting:
```
hr run robot
tmux a
```
Terminal 0 shows a fast spew of messages. One of these is:
```
Traceback (most recent call last):
  File "/home/hanson/hansonrobotics/HEAD/src/webui/scripts/motors_controller.py", line 141, in <module>
    MotorsController()
  File "/home/hanson/hansonrobotics/HEAD/src/webui/scripts/motors_controller.py", line 40, in __init__
    self.assemblies = rospy.get_param('/assemblies')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 462in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msproxy.py", line 123,
 in __getitem__
    raise KeyError(key)
KeyError: '/assemblies'
```

**Comment by linas** [comment]
This problem persists even after the `hr install -f head` as suggested in issue #12. Basically, there's a never-ending loop of 
```
process[webui/motors_controller-18]: started with pid [17421]
...
KeyError: '/assemblies'
[webui/motors_controller-18] process has died [pid 17421, exit code 1, cmd /home
/hanson/hansonrobotics/HEAD/src/webui/scripts/motors_controller.py __name:=motor
s_controller __log:=/home/hanson/.hr/log/8eb1a702-d552-11e7-b64e-80a5892a5999/we
bui-motors_controller-18.log].
log file: /home/hanson/.hr/log/8eb1a702-d552-11e7-b64e-80a5892a5999/webui-motors
_controller-18*.log
[webui/motors_controller-18] restarting process
process[webui/motors_controller-18]: started with pid [17449]
```

**Comment by linas** [comment]
This is a system not attached to any robot.

**Comment by linas** [comment]
Hmm. when I do `hr role user`, then this spew does not happen.  Instead I get the messages in issue #19
