### ISSUE TITLE
error message spew: pysptk

### ISSUE THREAD

**Issue by linas** [hansonrobotics/hrtool#15]
After following instructions for the README, installing and starting:
```
hr run robot
tmux a
```
Terminal 0 shows a fast spew of messages. One of these is:
```
Traceback (most recent call last):  
  File "/home/hanson/hansonrobotics/HEAD/src/ros_tts/scripts/tts_talker.py", line 30, in <module>
    from ttsserver.espp.emotivespeech import DEFAULT_PARAMS, PRESET_EMO_PARAMS
  File "/home/hanson/hansonrobotics/HEAD/devel/lib/python2.7/dist-packages/ttsserver/espp/emotivespeech.py", line 5, in <module>
    import batchprocess as bp
  File "/home/hanson/hansonrobotics/HEAD/devel/lib/python2.7/dist-packages/ttsserver/espp/batchprocess.py", line 2, in <module>
    import analysis as alysis
  File "/home/hanson/hansonrobotics/HEAD/devel/lib/python2.7/dist-packages/ttsserver/espp/analysis.py", line 5, in <module>
    import pysptk
ImportError: No module named pysptk
```

**Comment by linas** [comment]
Perhaps this explains one of the error messages in issue #11 ?

**Comment by linas** [comment]
Attempting to fix this with `sudo pip install pysptk`...

**Comment by linas** [comment]
... and that does NOT make the error message go away. I'm stumped.

**Comment by linas** [comment]
The `hr install -f head` as suggested in issue #12 makes this problem go away.
