### ISSUE TITLE
When role is `user`, get assorted errors.

### ISSUE THREAD

**Issue by linas** [hansonrobotics/hrtool#19]
I changed role to `user` from `developer` and then ran `hr run robot`.  It then goes into an infinite loop printing `[INFO] Waiting for master` 

i.e. `hr role user`

**Comment by wenwei-dev** [comment]
Yeah. That's a known issue. It's due to the recent changes of new organization of configs.

**Comment by wenwei-dev** [comment]
This should have been fixed.

**Comment by linas** [comment]
Yes, that message went away; I now get new messages: 
```
[rospy.internal][ERROR] [1512000078.887614]: Unable to initiate TCP/IP socket to lundborg:47921 (http://lundborg:36837/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [hr_msgs/TTS] vs. [std_msgs/String]
```

**Comment by linas** [comment]
And this one is different:
```
[rospy.internal][ERROR] [1512000077.432156]: Unable to initiate TCP/IP socket to
 lundborg:55869 (http://lundborg:48130/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: topic types do not match: [hr_msgs/ChatMessage] vs. [chatbot/ChatMessage]
```

**Comment by linas** [comment]
And some others:
```
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/joint_state_publisher/joint_state_publisher", line 5, in <module>
    import wx
ImportError: No module named wx
```
There's also the below, which seems to be associated with the default config, which is han:
```
[hr.pau2motors.pau2motors_node][ERROR] [1512000069.351551]: motor EyeTurn-R has no configuration
[hr.pau2motors.pau2motors_node][ERROR] [1512000069.353306]: motor EyeTurn-L has no configuration
[hr.pau2motors.pau2motors_node][ERROR] [1512000069.353482]: motor Eyes-Up-Down has no configuration
[hr.pau2motors.pau2motors_node][ERROR] [1512000069.360658]: motor EyeTurn-R has no configuration
[hr.pau2motors.pau2motors_node][ERROR] [1512000069.360859]: motor EyeTurn-L has no configuration
[hr.pau2motors.pau2motors_node][ERROR] [1512000069.361025]: motor Eyes-Up-Down has no configuration
process[webui/motors_controller-18]: started with pid [19462]
[rosout][ERROR] [1512000069.513482]: Cant load Expression Neutral
[rosout][ERROR] [1512000069.513984]: Cant load Expression Smile
```
